stages:
  - build
  - deploy

# Собираем фронтенд
build_frontend:
  stage: build
  image: node:20-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci
    - echo "VITE_API_URL=${VITE_API_URL}" > .env
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main

# Деплой на test.wooddon.ru
deploy_test:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    # 1. Деплоим фронт
    - rsync -az --delete dist/ root@$SERVER_IP:/var/www/wooddon.ru/data/www/test.wooddon.ru/dist/

    # 2. Деплоим бэкенд
    - rsync -az --delete --exclude 'venv' --exclude '.env' --exclude '__pycache__' --exclude '*.sqlite3' --exclude 'media' backend/ root@$SERVER_IP:/var/www/wooddon.ru/data/www/test.wooddon.ru/backend/

    # 3. Выполняем команды на сервере (Исправлен синтаксис для YAML)
    - |
      ssh root@$SERVER_IP '
        set -e
        cd /var/www/wooddon.ru/data/www/test.wooddon.ru/backend
        source venv/bin/activate
        pip install -r requirements.txt -q
        python manage.py migrate --no-input
        python manage.py collectstatic --no-input --clear
        chown -R wooddon.ru:wooddon.ru /var/www/wooddon.ru/data/www/test.wooddon.ru/
        systemctl restart gunicorn
        systemctl restart django-app.service
        echo "Deploy done"
      '
      
  only:
    - main
  environment:
    name: test
    url: https://test.wooddon.ru