# Generated by Django 5.1.1 on 2024-09-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttype_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='value',
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='products.product'),
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.characteristic')),
            ],
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='characteristic_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.characteristicvalue'),
        ),
    ]
