# Generated by Django 5.1.1 on 2024-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_custom_url_product_price_per_cubic_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
