# Generated by Django 5.1.1 on 2024-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_newslettersubscriber_alter_order_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_linear_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
