# Generated by Django 5.1.1 on 2024-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_price_per_linear_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, null=True, verbose_name='Товары'),
        ),
    ]
