# Generated by Django 5.1.6 on 2025-03-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_order_items'),
        ('products', 'add_default_image'),
    ]

    operations = [
    ]
