# Generated by Django 5.1.6 on 2025-03-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_0012_alter_order_items_add_default_image'),
        ('products', 'add_measurement_fields'),
    ]

    operations = [
    ]
