# Generated by Django 5.1.6 on 2025-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20250321_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за м³'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_linear_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за погонный метр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за штуку'),
        ),
    ]
