# Generated by Django 5.1.6 on 2025-04-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_package',
            field=models.IntegerField(default=1, help_text='Количество штук в одной пачке', verbose_name='Штук в пачке'),
        ),
    ]
