# Generated by Django 5.1.6 on 2026-02-25 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_pieces_per_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='products_er_timesta_233ed9_idx'), models.Index(fields=['is_resolved', '-timestamp'], name='products_er_is_reso_276a90_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('view_product', 'Просмотр товара'), ('add_to_cart', 'Добавление в корзину'), ('remove_from_cart', 'Удаление из корзины'), ('toggle_favorite', 'Изменение избранного'), ('create_order', 'Создание заказа'), ('view_products', 'Просмотр списка товаров'), ('newsletter_subscribe', 'Подписка на рассылку'), ('search', 'Поиск'), ('click', 'Клик по элементу'), ('page_view', 'Просмотр страницы'), ('time_on_page', 'Время на странице')], db_index=True, max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('duration', models.FloatField(blank=True, help_text='Время выполнения в секундах', null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action_type'], name='products_us_timesta_23f1e3_idx'), models.Index(fields=['session_key', '-timestamp'], name='products_us_session_38faf5_idx'), models.Index(fields=['ip_address', '-timestamp'], name='products_us_ip_addr_0a8f04_idx')],
            },
        ),
    ]
