# Generated by Django 4.2.20 on 2026-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_quizlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
